# Generated by Django 2.2.6 on 2019-10-11 13:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date')),
                ('channel', models.CharField(max_length=50, verbose_name='channel')),
                ('country', models.CharField(max_length=10, verbose_name='country')),
                ('os', models.CharField(max_length=6, verbose_name='os')),
                ('impressions', models.PositiveIntegerField(verbose_name='impressions')),
                ('clicks', models.PositiveSmallIntegerField(verbose_name='clicks')),
                ('installs', models.PositiveSmallIntegerField(verbose_name='installs')),
                ('spend', models.FloatField(verbose_name='installs')),
                ('revenue', models.FloatField(verbose_name='revenue')),
            ],
        ),
    ]
